name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name : Clang Format
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: './src/'
          extensions: 'h,cpp'
          clangFormatVersion: 13
          inplace: True

      - name: Commit formatting diff
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Clang Robot
          author_email: clang-robot@lesma.com
          message: 'Committing clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-13.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build
        run: |
          cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

      - uses: actions/upload-artifact@v2
        with:
          name: lesma
          path: ${{github.workspace}}/build/lesma