name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Release
  CC: clang
  CXX: clang++

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Clang Format
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: './src/'
          extensions: 'h,cpp'
          clangFormatVersion: 14
          inplace: True

      - name: Commit formatting diff
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Clang Robot
          author_email: clang-robot@lesma.com
          message: 'Committing clang-format changes'

      - name: Get vcpkg commit hash
        id: vcpkg_hash
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'vcpkg.json'
          prop_path: 'builtin-baseline'

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@v3.26.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@11
        id: runvcpkg
        with:
          vcpkgGitCommitId: '${{ steps.vcpkg_hash.outputs.propStr }}'

      - name: Run CMake with Ninja
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/cmakepresets/CMakeLists.txt'
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

      - name: Package Artifact
        working-directory: ${{github.workspace}}/build
        run: ninja package

      - uses: actions/upload-artifact@v3
        with:
          name: lesma
          path: ${{github.workspace}}/build/Lesma*.tar.gz

  release:
    name: Release
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Semantic Release Dependencies
        run: |
          npm install -g @semantic-release/changelog @semantic-release/git

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: lesma

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}